---
image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
stages:
  - test
  - deploy
branches: feature/chat app
before_script:
  - npm ci
jest-tests:
  stage: test
  script:
    - npx jest --ci
  when:
    event: push
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive
  when:
    event: push
